name: studentvueclient
description: a client library for the student vue grade system
version: 0.0.7
repository: https://github.com/StudentVue/StudentVue.dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dio: ^3.0.10
  xml: ^4.0.0
  html_unescape: ^1.0.1+3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
